### ISSUE TITLE
rctl commands with '?' formatting

### ISSUE THREAD

**Issue by mphoebos** [fonoster/routr#38]
Hi All. I've started recently playing around with Routr and I'm having a particular issue probably related with the Java that I have installed on Debian. Every time I run a rctl command, the formatting is not as it should be. This didn't happen when I was running CentOS. Can you please provide me more information about what ideal Java packages are required? Here is how it looks:
![image](https://user-images.githubusercontent.com/45604712/59919802-55271600-9420-11e9-9624-93739dd9f0a8.png)

**Comment by psanders** [comment]
@mphoebos I was able to reproduce this issue in windows, and it seems to be an encoding issue. The dependency we are using to display the tables is using the OS's default encoding(which sometimes does not support the characters needed to generate the table). 

A workaround this issue is to change the OS default encoding to UTF8 or simply set environment variable `JAVA_TOOL_OPTIONS` to `-Dfile.encoding=UTF8`. The next version of the command line tool will fix this problem.
