### ISSUE TITLE
The Web Console throws an error on saving the Certificates section

### ISSUE THREAD

**Issue by philiplb** [fonoster/routr#69]
Hi,

I'm running routr 1.0 RC4 on Ubuntu 18.04 via Snap.
Unfortunately I can't save the Certificate settings in the web console. As soon as I hit the Save button, it just throws an error "TypeError: t.localnets is undefined" on the console and stops there.

**Comment by psanders** [comment]
Can you save any other settings? I can't save settings at al, but no error on the console. Which version of the cli (rctl) are you using?

**Comment by philiplb** [comment]
Hi,
thanks for the answer. I can't save any setting. This is my version of the cli:

> npm list -g | grep routr-ctl
>└─┬ routr-ctl@1.0.13

**Comment by philiplb** [comment]
One question, how would I change such a setting on the CLI with rctl?

**Comment by psanders** [comment]
@philiplb 

I created a [fix](https://github.com/fonoster/routr-ctl/commit/e6245d5b8ecb590bf713031ce8b7c3c6bcb00f21) this issue. This will be available at NPM probably this weekend. However, you can install rctl 1.0.14 (with fix for the Web UI) directly from the repository, using the following command:

```bash
npm install https://github.com/fonoster/routr-ctl -g
```

> One question, how would I change such a setting on the CLI with rctl?

Unfortunately this is not [possible yet](https://github.com/fonoster/routr-ctl/issues/5), but I'm tracking the issue.

> One thing I just tried: I changed the file /var/snap/routr-server/13/config/config.yml to

This is the expected behavior. When you set `spec.datasource.provider` to a persistent data provider, the configuration is store in that data provider. I can see how that may be confusing. Perhaps we should update the documentation.

**Comment by psanders** [comment]
Oh I forgot to mention, that you might see an error related to the `trustStore` and the `trustStorePassword` being null. This is and issue with Routr setting those values to null as default. I already fix it and will be available in RC5. 

As a workaround, go to `Settings -> Rest Service` and set the trustStore and trustStorePassword to ANY value and save the settings. After that you can come back and remove those values.

Sorry for the inconvenience.

**Comment by philiplb** [comment]
That worked well!
Now I can't get sip.js connected to the Routr instance, but I need to investigate deeper here. It can't connect to the Websocket so far. Maybe I will open another issue later.

Thank you very much! :)
